/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugSupplier;

import Business.Doctor.Patient;
import Business.Drug.Drug;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Gene.Gene;
import Business.Network.Network;
import Business.Organization.DrugOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DrugWorkRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PharmacyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userinterface.LabAssistantRole.ProcessWorkRequestJPanel;

/**
 *
 * @author kasai
 */
public class LabResultsJpanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DrugOrganization drugOrganization;
    private Enterprise enterprise;
    private Network network;
    private static Logger log = Logger.getLogger(LabResultsJpanel.class);
    private static final String CLASS_NAME = LabResultsJpanel.class.getName();

    /**
     * Creates new form LabResultsJpanel
     */
    public LabResultsJpanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, DrugOrganization drugOrganization, Network network,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.drugOrganization = drugOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        generateDrugJButton = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Age", "Sex", "Message", "Sender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestJTable.setRowHeight(30);
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 152, 900, 290));

        generateDrugJButton.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 20)); // NOI18N
        generateDrugJButton.setForeground(new java.awt.Color(0, 0, 102));
        generateDrugJButton.setText("Generate Drug");
        generateDrugJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateDrugJButtonActionPerformed(evt);
            }
        });
        add(generateDrugJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 210, 40));

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\vgout\\AED_ASSIGNMENT\\AED_ASSIGNMENT_LAB\\biogen_finalproject\\BioGen_FinalProject\\src\\Image\\backbtn")); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, 33));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Lab Results");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, 53));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DrugLabResults.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : drugOrganization.getWorkQueue().getWorkRequestList()) {

            if (((DrugWorkRequest) request).getPatient() != null) {
                Object[] row = new Object[7];
                row[0] = ((DrugWorkRequest) request).getPatient();
                row[1] = ((DrugWorkRequest) request).getPatient().getAge();
                row[2] = ((DrugWorkRequest) request).getPatient().getSex();
                row[3] = ((DrugWorkRequest) request).getPatient().getTest();

                row[4] = request.getSender().getEmployee().getName();
                               model.addRow(row);
            }
        }

    }

    private void generateDrugJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateDrugJButtonActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();

         if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        
        int flag = 0;
        Patient patient = (Patient) workRequestJTable.getValueAt(selectedRow, 0);
        if(patient.getNewDrug()!=null)
        {
            JOptionPane.showMessageDialog(null, "Drug has been identified already");
        }
        
        List<String> patientGene = new ArrayList<>();
        for (int i = 0; i < patient.getGeneHistory().getGeneHistory().size(); i++) {
            Gene g = patient.getGeneHistory().getGeneHistory().get(i);
            patientGene.add(g.getGeneName());

        }
        Collections.sort(patientGene);
        List<String> totaldrugGene = new ArrayList<>();
        for (Drug d : business.getDrugList().getDrugList()) {
            List<String> drugGene = new ArrayList<>();
            for (int i = 0; i < d.getGeneHistory().getGeneHistory().size(); i++) {
                Gene g = d.getGeneHistory().getGeneHistory().get(i);
                drugGene.add(g.getGeneName());
                totaldrugGene.add(g.getGeneName());
            }
            Collections.sort(drugGene);

            if (drugGene.equals(patientGene)) {
                ExistingDrugResultsJpanel existingDrugResultsJpanel = new ExistingDrugResultsJpanel(userProcessContainer, userAccount, enterprise, drugOrganization, network, d);

                userProcessContainer.add("existingDrugResultsJpanel", existingDrugResultsJpanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                flag = 1;
            }

        }
        System.out.println(totaldrugGene.containsAll(patientGene));
         if (!totaldrugGene.containsAll(patientGene)) {
                NonExistingGeneJpanel nonExistingGeneJpanel = new NonExistingGeneJpanel(userProcessContainer, userAccount, enterprise, drugOrganization, network);

                userProcessContainer.add("nonExistingGeneJpanel", nonExistingGeneJpanel);
                log.debug(userAccount+" "+"entering nonexisting page as drug doesn't exist");
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                flag = 2;
            }
        

        if (flag == 0) {
            GenerateDrugNewDrugJPanel generateDrugNewDrugJPanel = new GenerateDrugNewDrugJPanel(userProcessContainer, patient, drugOrganization, userAccount, network,business);

            userProcessContainer.add("generateDrugNewDrugJPanel", generateDrugNewDrugJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            log.debug(userAccount+" "+"entering new drug page as no drug exists");
            layout.next(userProcessContainer);
        }


    }//GEN-LAST:event_generateDrugJButtonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DrugSupplierWorkArea dwjp = (DrugSupplierWorkArea) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton generateDrugJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
