/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugSupplier;

import Business.WorkQueue.DrugWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author kasai
 */
public class ProcessDrugWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ProcessDrugWorkRequest
     */
    
    JPanel userProcessContainer;
    DrugWorkRequest request;
    private static Logger log = Logger.getLogger(ProcessDrugWorkRequest.class);
    private static final String CLASS_NAME = ProcessDrugWorkRequest.class.getName();
    public ProcessDrugWorkRequest(JPanel userprocessContainer,DrugWorkRequest request) {
        initComponents();
        this.userProcessContainer=userprocessContainer;
        this.request=request;
        dateFld.setMinSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        dateTxt = new javax.swing.JTextField();
        dateFld = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("PROCESSING SUPPLIER REQUEST ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 64, -1, 53));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("SELECT DATE OF DELIVERY : ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 212, 375, 41));

        updateBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(0, 0, 102));
        updateBtn.setText("UPDATE STATUS ");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 345, 261, 50));

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\vgout\\AED_ASSIGNMENT\\AED_ASSIGNMENT_LAB\\biogen_finalproject\\BioGen_FinalProject\\src\\Image\\backbtn")); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 345, -1, 50));

        dateTxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        dateTxt.setForeground(new java.awt.Color(0, 0, 102));
        dateTxt.setEnabled(false);
        add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 212, 261, 41));
        add(dateFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 212, 156, 41));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/progress.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
      
       request.setStatus("Completed");
       try{ 
           int year=dateFld.getCalendar().get(Calendar.YEAR);
        int month=dateFld.getCalendar().get(Calendar.MONTH);
        int day=dateFld.getCalendar().get(Calendar.DAY_OF_MONTH);
         String result=year+"-"+month+"-"+day;
           ((DrugWorkRequest) request).setDeliveryTime(result);
        dateTxt.setText(result);
       }
       catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, "please enter the delivery date ");
            return;
       }
       
       
        
       
        JOptionPane.showMessageDialog(null, "Request updated successfully!");
        log.debug("delivery date updated");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DrugSupplierWorkArea dwjp = (DrugSupplierWorkArea) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser dateFld;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
