/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugSupplier;

/**
 *
 * @author kasai
 */
public class ViewLabTestResultsJapnel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLabTestResultsJapnel
     */
    public ViewLabTestResultsJapnel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        geneTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 22)); // NOI18N
        patientTextField.setEnabled(false);
        add(patientTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 180, -1));

        geneTbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        geneTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Gene"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        geneTbl.setRowHeight(30);
        geneTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(geneTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 317, -1, 200));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText(" LAB TEST RESULTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 480, 52));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Patient Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 200, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/DrugLabResults.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable geneTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientTextField;
    // End of variables declaration//GEN-END:variables
}
