/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugSupplier;

import Business.ChemicalInventory.ChemicalCompound;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.MedicalInventory.MedicalInventory;
import Business.Network.Network;
import Business.Organization.DrugOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ChemicalWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import userinterface.PharmacyRole.ViewDetailsJPanel;

/**
 *
 * @author kasai
 */
public class ViewChemicalRequestsJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DrugOrganization drugOrganization ;
    private Enterprise enterprise;
    private Network network;
    private static Logger log = Logger.getLogger(ViewChemicalRequestsJPanel.class);
    private static final String CLASS_NAME = ViewChemicalRequestsJPanel.class.getName();

    /**
     * Creates new form ViewChemicalRequestsJPanel
     */
    public ViewChemicalRequestsJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise, DrugOrganization drugOrganization,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.drugOrganization = drugOrganization;
        this.enterprise = enterprise;
        this.network = network;
        reorderTable();
    }
   
    public void reorderTable(){
        int rowCount = reorderTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)reorderTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
      for(ChemicalCompound mi : drugOrganization.getChemList()){
            Object row[] = new Object[6];
            row[0] = mi;
            row[1] = mi.getSerialNumber();
            row[2]= mi.getAvailQuantity();
            row[3]=mi.getRequiredQuantity();
            row[4]= mi.getReorderStatus();
            //row[5]=mi.getReorderStatus();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reorderTable = new javax.swing.JTable();
        addMedicineButton = new javax.swing.JButton();
        viewRequestsButton = new javax.swing.JButton();
        viewDetailsButton1 = new javax.swing.JButton();
        statusCheckButton = new javax.swing.JButton();
        serialNumLabel = new javax.swing.JLabel();
        serialNumberTextField = new javax.swing.JTextField();
        medicineNameLabel = new javax.swing.JLabel();
        chemicalNameTextField = new javax.swing.JTextField();
        availQuantityLabel = new javax.swing.JLabel();
        availQuantityTextField = new javax.swing.JTextField();
        reqQuantityLabel = new javax.swing.JLabel();
        reqQuantityTextField = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reorderTable.setBorder(new javax.swing.border.MatteBorder(null));
        reorderTable.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        reorderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CHEMICAL NAME", "SERIAL NUMBER ", "AVAILABILE QUANTITY", "REQUIRED QUANTITY", "REORDER STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reorderTable.setRowHeight(30);
        jScrollPane1.setViewportView(reorderTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 149, 950, 238));

        addMedicineButton.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        addMedicineButton.setForeground(new java.awt.Color(0, 0, 102));
        addMedicineButton.setText("ADD CHEMICAL");
        addMedicineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedicineButtonActionPerformed(evt);
            }
        });
        add(addMedicineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 616, 251, -1));

        viewRequestsButton.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        viewRequestsButton.setText("VIEW REQUESTS");
        viewRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequestsButtonActionPerformed(evt);
            }
        });
        add(viewRequestsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 400, 251, -1));

        viewDetailsButton1.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        viewDetailsButton1.setText("VIEW DETAILS");
        viewDetailsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButton1ActionPerformed(evt);
            }
        });
        add(viewDetailsButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 440, 251, -1));

        statusCheckButton.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        statusCheckButton.setText("INVENTORY STATUS CHECK");
        statusCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCheckButtonActionPerformed(evt);
            }
        });
        add(statusCheckButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 321, -1));

        serialNumLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        serialNumLabel.setForeground(new java.awt.Color(0, 0, 102));
        serialNumLabel.setText("SERIAL NUMBER: ");
        add(serialNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 409, -1, 20));

        serialNumberTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        add(serialNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 399, 270, -1));

        medicineNameLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        medicineNameLabel.setForeground(new java.awt.Color(0, 0, 102));
        medicineNameLabel.setText("CHEMICAL NAME: ");
        add(medicineNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 447, -1, -1));

        chemicalNameTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        add(chemicalNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 445, 270, -1));

        availQuantityLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        availQuantityLabel.setForeground(new java.awt.Color(0, 0, 102));
        availQuantityLabel.setText("AVAILABLE QUANTITY:");
        add(availQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 492, 282, 20));

        availQuantityTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        add(availQuantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 492, 270, -1));

        reqQuantityLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        reqQuantityLabel.setForeground(new java.awt.Color(0, 0, 102));
        reqQuantityLabel.setText("REQUIRED QUANTITY:");
        add(reqQuantityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 544, 280, 20));

        reqQuantityTextField.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 20)); // NOI18N
        reqQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqQuantityTextFieldActionPerformed(evt);
            }
        });
        add(reqQuantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 539, 270, -1));

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\vgout\\AED_ASSIGNMENT\\AED_ASSIGNMENT_LAB\\biogen_finalproject\\BioGen_FinalProject\\src\\Image\\backbtn")); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 692, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Chemical Requests");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 53));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Request.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 13, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addMedicineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicineButtonActionPerformed
        // TODO add your handling code here:

        ChemicalCompound m=new ChemicalCompound();
        String name=chemicalNameTextField.getText().trim();      
        if(name.isEmpty())
        {
         JOptionPane.showMessageDialog(null,"Chemical Name is empty");
            return;   
        }
        m.setChemicalName(chemicalNameTextField.getText());
        try
        {
        int availableQuantity= Integer.parseInt(availQuantityTextField.getText());
        m.setAvailQuantity(availableQuantity);
        }
        catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(null,"available quantity must be a integer");
            return;   
        }
        try
        {
        int serialNumber= Integer.parseInt(serialNumberTextField.getText());
        m.setSerialNumber(serialNumber);
        }
         catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(null,"Serial number  must be a integer");
            return;   
        }
        try{
        int requiredQuantity= Integer.parseInt(reqQuantityTextField.getText());
        m.setRequiredQuantity(requiredQuantity);
        }
         catch(NumberFormatException e){

            JOptionPane.showMessageDialog(null,"Required quantity must be integer!");
            return;
        }
//        ArrayList<String> chemicalCheck = new ArrayList<>();
//        for(ChemicalCompound mi : drugOrganization.getChemList())
//        {
//            chemicalCheck.add(mi.getChemicalName().toLowerCase());
//        }
//        if(chemicalCheck.contains(name.toLowerCase()))
//        {
//            JOptionPane.showMessageDialog(null, "chemical name already existed please update the quantity by clicking on view details");
//            return;
//        }
        drugOrganization.addChemical(m);
        m.setReorderStatus("N");

        DefaultTableModel dtm =(DefaultTableModel) reorderTable.getModel();

        dtm.setRowCount(0);
        for(ChemicalCompound mi : drugOrganization.getChemList()){
            Object row[] = new Object[5];
            row[0] = mi;
            row[1] = mi.getSerialNumber();
            row[2]= mi.getAvailQuantity();
            row[3]=mi.getRequiredQuantity();
            row[4]= mi.getReorderStatus();
            dtm.addRow(row);
        }

        JOptionPane.showMessageDialog(null, "Chemical Added Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
        serialNumberTextField.setText("");
        chemicalNameTextField.setText("");
        availQuantityTextField.setText("");
        reqQuantityTextField.setText("");
        log.debug(userAccount+" "+"added chemical"+name);
        
    }//GEN-LAST:event_addMedicineButtonActionPerformed

    private void viewRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequestsButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       userProcessContainer.add("ViewRequestJPanel", new ViewRequestsJPanel( userProcessContainer, userAccount, enterprise, drugOrganization));
        layout.next(userProcessContainer);
        log.debug("entering view chemical requests page");

    }//GEN-LAST:event_viewRequestsButtonActionPerformed

    private void viewDetailsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButton1ActionPerformed
        // TODO add your handling code here:
        int row = reorderTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ChemicalCompound mi = (ChemicalCompound)reorderTable.getValueAt(row, 0);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("UpdateEntryJPanel", new ViewChemicalDetailsJPanel(userProcessContainer, userAccount, enterprise,mi));
        layout.next(userProcessContainer);
        log.debug(userAccount+" "+"entering view chemical details page");
    }//GEN-LAST:event_viewDetailsButton1ActionPerformed

    private void statusCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCheckButtonActionPerformed
        // TODO add your handling code here:
        int i=0;
        for(ChemicalCompound mi : drugOrganization.getChemList()){
            i++;
            
        }
        if(i<=0)
        {
            JOptionPane.showMessageDialog(null,"No chemicals are present for invetory check  ");
            return;
        }
      for(ChemicalCompound mi : drugOrganization.getChemList()){

            if(mi.getAvailQuantity()<=mi.getRequiredQuantity()){
                if(!mi.getReorderStatus().equals("Y")){
                    ChemicalWorkRequest request=new ChemicalWorkRequest();

                    mi.setReorderStatus("Y");
                    request.setChemicalName(mi.getChemicalName());
                    request.setQuantity(mi.getRequiredQuantity());
                    request.setSender(userAccount);

                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                    for(Enterprise enterprise :network.getEnterpriseDirectory().getEnterpriseList() ){
                        System.out.println("***** Organization Name:" +enterprise.getName());
                        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                            System.out.println("***** Organization Name:" +organization.getName());
                            if(organization.getName().equals("Chemical Organization")){
                                System.out.println("True");

                                System.out.println("***** organization Name"+organization.getName());

                                organization.getWorkQueue().getWorkRequestList().add(request);
                                log.debug("chemical request has been sent to chemical organization");
                            }
                        }

                    }

                }

            }
        } 
        JOptionPane.showMessageDialog(null, "Inventory status checked and updated!", "Warning", JOptionPane.INFORMATION_MESSAGE);
       reorderTable();
    }//GEN-LAST:event_statusCheckButtonActionPerformed

    private void reqQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reqQuantityTextFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DrugSupplierWorkArea dwjp = (DrugSupplierWorkArea) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedicineButton;
    private javax.swing.JLabel availQuantityLabel;
    private javax.swing.JTextField availQuantityTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField chemicalNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel medicineNameLabel;
    private javax.swing.JTable reorderTable;
    private javax.swing.JLabel reqQuantityLabel;
    private javax.swing.JTextField reqQuantityTextField;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JTextField serialNumberTextField;
    private javax.swing.JButton statusCheckButton;
    private javax.swing.JButton viewDetailsButton1;
    private javax.swing.JButton viewRequestsButton;
    // End of variables declaration//GEN-END:variables
}
