/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Chemical.Chemical;
import Business.Enterprise.ChemicalEnterprise;
import Business.Enterprise.DrugEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author vgout
 */
public class ManageOrganizationJpanel extends javax.swing.JPanel {

      private OrganizationDirectory organizationDir;
      private JPanel userProcessContainer;
      private Enterprise enterprise;
      private static Logger log = Logger.getLogger(ManageOrganizationJpanel.class);
      private static final String CLASS_NAME = ManageOrganizationJpanel.class.getName();
    /**
     * Creates new form ManageOrganizationJpanel
     */
    public ManageOrganizationJpanel(JPanel userProcessContainer,OrganizationDirectory organizationDir,Enterprise enterprise) {
        initComponents();
        this.organizationDir = organizationDir;
        this.userProcessContainer = userProcessContainer;
        this.enterprise=enterprise;
        populateTable();
        populateComboBox();
        
    }
    private void populateComboBox(){
        organizationComboBox.removeAllItems();
        for (Organization.Type type : Organization.Type.values()){
            
            if (!type.getValue().equals(Organization.Type.Admin.getValue()))
            {
//                
                if(enterprise instanceof HospitalEnterprise){
                    
                     organizationComboBox.addItem(Organization.Type.Doctor);
                     organizationComboBox.addItem(Organization.Type.Lab);
                     break;
                }else if(enterprise instanceof PharmacyEnterprise){
                    
                     organizationComboBox.addItem(Organization.Type.Pharmacy);
                     break;
                    
                }
                else if(enterprise instanceof DrugEnterprise)
                {
                     organizationComboBox.addItem(Organization.Type.Drug);
                     break;
                }
                else if(enterprise instanceof ChemicalEnterprise)
                {
                  organizationComboBox.addItem(Organization.Type.Chemical);
                     break;  
                }
                 
                    
            }
        }
    }
     private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationtbl.getModel();
        
        model.setRowCount(0);
        
        for (Organization organization : organizationDir.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageorglbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationtbl = new javax.swing.JTable();
        orglbl = new javax.swing.JLabel();
        organizationComboBox = new javax.swing.JComboBox();
        backbtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(52, 148, 172));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageorglbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        manageorglbl.setForeground(new java.awt.Color(0, 0, 102));
        manageorglbl.setText("Manage Organization");
        add(manageorglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 68, -1, -1));

        organizationtbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        organizationtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        organizationtbl.setRowHeight(22);
        organizationtbl.getTableHeader().setResizingAllowed(false);
        organizationtbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(organizationtbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 198, 516, 177));

        orglbl.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 24)); // NOI18N
        orglbl.setText("Organization Type: ");
        add(orglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 444, -1, -1));

        organizationComboBox.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 20)); // NOI18N
        organizationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(organizationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 450, 200, 32));

        backbtn.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 0, 102));
        backbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\vgout\\AED_ASSIGNMENT\\AED_ASSIGNMENT_LAB\\biogen_finalproject\\BioGen_FinalProject\\src\\Image\\backbtn")); // NOI18N
        backbtn.setText(" Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        addBtn.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 102));
        addBtn.setText("Add Organization");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 538, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        Type type = (Type) organizationComboBox.getSelectedItem();
        organizationDir.createOrganization(type);
        log.debug("Enterprise admin adding the following Organization" +type);
        populateTable();
        
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageorglbl;
    private javax.swing.JComboBox organizationComboBox;
    private javax.swing.JTable organizationtbl;
    private javax.swing.JLabel orglbl;
    // End of variables declaration//GEN-END:variables
}
