/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

/**
 *
 * @author kasai
 */
public class ClincalTrailJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClincalTrailJPanel
     */
    private JPanel userProcessContainer;
    private LabTestWorkRequest request;
    private static Logger log = Logger.getLogger(ClincalTrailJPanel.class);
    private static final String CLASS_NAME = ClincalTrailJPanel.class.getName();
    public ClincalTrailJPanel(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        patientTxtField.setText(request.getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientLbl = new javax.swing.JLabel();
        patientTxtField = new javax.swing.JTextField();
        LabTestLbl = new javax.swing.JLabel();
        sexcomboBox = new javax.swing.JComboBox<String>();
        patientLbl1 = new javax.swing.JLabel();
        statusUpdate = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientLbl.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        patientLbl.setForeground(new java.awt.Color(0, 0, 102));
        patientLbl.setText("Patient Name :");
        add(patientLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 226, 180, 30));

        patientTxtField.setEditable(false);
        add(patientTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 226, 200, 30));

        LabTestLbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48)); // NOI18N
        LabTestLbl.setForeground(new java.awt.Color(0, 0, 102));
        LabTestLbl.setText(" CLINICAL TRAIL STATUS");
        add(LabTestLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 34, 609, 52));

        sexcomboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Please select--", "Success", "Failure" }));
        add(sexcomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 311, 200, -1));

        patientLbl1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 24)); // NOI18N
        patientLbl1.setForeground(new java.awt.Color(0, 0, 102));
        patientLbl1.setText("Status");
        add(patientLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 303, 180, 30));

        statusUpdate.setForeground(new java.awt.Color(0, 0, 102));
        statusUpdate.setText("SUBMIT");
        statusUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusUpdateActionPerformed(evt);
            }
        });
        add(statusUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 405, 135, 41));

        backBtn.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 102));
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 401, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/clinical.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 34, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void statusUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusUpdateActionPerformed
        // TODO add your handling code here:
        
         
        String clinicalStatus = sexcomboBox.getSelectedItem().toString();
        
        if((clinicalStatus == "") || (!clinicalStatus.equalsIgnoreCase("--Please select--"))){
            
            request.getPatient().setClinicalStatus(clinicalStatus);
            log.debug("updated patient status to"+" "+request.getPatient().getClinicalStatus());
            JOptionPane.showMessageDialog(null, "Status has been updated successfully");
    }
        
        else{
            JOptionPane.showMessageDialog(null, "Please select clincal Status");
            log.error("clinical status has not been selected");
        }
    }//GEN-LAST:event_statusUpdateActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorRequestJpanel dwjp = (DoctorRequestJpanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTestLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel patientLbl;
    private javax.swing.JLabel patientLbl1;
    private javax.swing.JTextField patientTxtField;
    private javax.swing.JComboBox<String> sexcomboBox;
    private javax.swing.JButton statusUpdate;
    // End of variables declaration//GEN-END:variables
}
