/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Doctor.Physician;
import Business.Doctor.PrescriptionList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;


/**
 *
 * @author vgout
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Physician physician;
    private PrescriptionList list;
    private DoctorWorkRequest docreq;
    private Network network;
    private EcoSystem system;
    private static Logger log = Logger.getLogger(DoctorWorkAreaJPanel.class);
    private static final String CLASS_NAME = DoctorWorkAreaJPanel.class.getName();

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        network();
    }

    public void network() {
        network.getName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrecriptionBtn = new javax.swing.JButton();
        labTestBtn = new javax.swing.JButton();
        doctorLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(2000, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PrecriptionBtn.setBackground(new java.awt.Color(255, 255, 255));
        PrecriptionBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        PrecriptionBtn.setForeground(new java.awt.Color(0, 0, 102));
        PrecriptionBtn.setText("WRITE PRESCRIPTION");
        PrecriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecriptionBtnActionPerformed(evt);
            }
        });
        add(PrecriptionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 147, 497, 83));

        labTestBtn.setBackground(new java.awt.Color(255, 255, 255));
        labTestBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        labTestBtn.setForeground(new java.awt.Color(0, 0, 102));
        labTestBtn.setText("Lab Test");
        labTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labTestBtnActionPerformed(evt);
            }
        });
        add(labTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 403, 497, 100));

        doctorLbl.setBackground(new java.awt.Color(0, 204, 204));
        doctorLbl.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 48)); // NOI18N
        doctorLbl.setForeground(new java.awt.Color(0, 0, 102));
        doctorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorLbl.setText("DOCTOR WORK AREA ");
        add(doctorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 49, -1, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Doctor.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 560, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void PrecriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecriptionBtnActionPerformed
        // TODO add your handling code here:

         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
          log.debug("inside doctor role");
          userProcessContainer.add("PrescriptionJPanel", new userinterface.DoctorRole.PrescriptionJPanel(userProcessContainer,list,userAccount,enterprise,organization,system,network));
       //  userProcessContainer.add("PrescriptionJPanel", new userinterface.DoctorRole.PrescriptionJPanel(userProcessContainer, userAccount, enterprise));
         layout.next(userProcessContainer);

    }//GEN-LAST:event_PrecriptionBtnActionPerformed

    private void labTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labTestBtnActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug("inside doctor's lab request");
        userProcessContainer.add("TestJPanel", new userinterface.DoctorRole.DoctorRequestJpanel(userProcessContainer, userAccount, organization, enterprise, system, network));

        layout.next(userProcessContainer);
    }//GEN-LAST:event_labTestBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PrecriptionBtn;
    private javax.swing.JLabel doctorLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton labTestBtn;
    // End of variables declaration//GEN-END:variables
}
